name: quick-aws-ec2 deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'quick-aws-ec2/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Starting environment'
        required: true
        type: choice
        options:
          - dev
          - prd
      promote:
        description: 'Promote to next environment'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    uses: mbasri-actions/reusable-workflows/.github/workflows/terraform-deploy.yml@main
    with:
      environment: ${{ inputs.environment || 'dev' }}
      working-directory: quick-aws-ec2
    secrets: inherit

  promote-prd:
    if: inputs.promote == true && inputs.environment == 'dev'
    needs: deploy
    uses: mbasri-actions/reusable-workflows/.github/workflows/terraform-deploy.yml@main
    with:
      environment: prd
      working-directory: quick-aws-ec2
    secrets: inherit
